'use client';

import { useState, useTransition } from 'react';
import { Sparkles, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';

interface Theme { label: string; evidence_summary: string; frequency: 'low'|'medium'|'high' }
interface Synthesis {
  themes: Theme[];
  sentiment_summary: string;
  notable_patterns: string[];
}

export function SynthesizeButton({ cohortId, initial }: { cohortId: string; initial?: Synthesis | null }) {
  const [synthesis, setSynthesis] = useState<Synthesis | null>(initial ?? null);
  const [pending, startTransition] = useTransition();
  const [error, setError] = useState<string | null>(null);

  const run = () => {
    setError(null);
    startTransition(async () => {
      try {
        const r = await fetch('/api/ai/synthesize-cohort', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ cohortId }),
        });
        const data = await r.json();
        if (!data.ok) throw new Error(data.error ?? 'Synthesis failed');
        setSynthesis(data.synthesis);
      } catch (e: any) {
        setError(e?.message ?? 'Unexpected error');
      }
    });
  };

  return (
    <div>
      <div className="flex items-center justify-between gap-3 mb-3">
        <div>
          <div className="text-[10.5px] uppercase tracking-[1.2px] text-ach-navy/60">Narrative synthesis (AI)</div>
          <div className="text-[11.5px] text-ach-navy/55 mt-0.5">Themes + sentiment summary from cohort observable-changes / practices / narrative responses. Generated by Azure OpenAI, reviewed by caseworker.</div>
        </div>
        <Button type="button" variant="secondary" onClick={run} disabled={pending}>
          {pending
            ? <><Loader2 className="h-3.5 w-3.5 animate-spin" />Analysing…</>
            : <><Sparkles className="h-3.5 w-3.5" />{synthesis ? 'Regenerate' : 'Generate'}</>}
        </Button>
      </div>

      {error && <div className="text-[12px] text-[#8B3A4F] bg-ach-rose/10 rounded-[10px] px-3 py-2 border-[0.5px] border-ach-rose/30 mb-3">{error}</div>}

      {synthesis ? (
        <div className="space-y-4">
          {synthesis.sentiment_summary && (
            <div>
              <div className="text-[10.5px] uppercase tracking-[1.2px] text-ach-navy/55 mb-1">Overall sentiment</div>
              <p className="text-[13px] text-ach-navy/85 italic">{synthesis.sentiment_summary}</p>
            </div>
          )}
          {(synthesis.themes ?? []).length > 0 && (
            <div>
              <div className="text-[10.5px] uppercase tracking-[1.2px] text-ach-navy/55 mb-2">Themes</div>
              <div className="space-y-2">
                {synthesis.themes.map((t, i) => (
                  <div key={i} className="p-3 rounded-[10px] border-[0.5px] border-ach-border bg-white">
                    <div className="flex items-center justify-between gap-2 mb-1">
                      <div className="text-[13px] font-medium text-ach-navy">{t.label}</div>
                      <span className={`text-[10px] uppercase tracking-[1px] font-medium px-2 py-0.5 rounded-full border-[0.5px] ${
                        t.frequency === 'high' ? 'bg-ach-slate-tint text-ach-slate-deep border-ach-slate-blue/30'
                        : t.frequency === 'medium' ? 'bg-ach-page text-ach-navy/70 border-ach-border'
                        : 'bg-white text-ach-navy/55 border-ach-border'
                      }`}>
                        {t.frequency}
                      </span>
                    </div>
                    <p className="text-[12px] text-ach-navy/75">{t.evidence_summary}</p>
                  </div>
                ))}
              </div>
            </div>
          )}
          {(synthesis.notable_patterns ?? []).length > 0 && (
            <div>
              <div className="text-[10.5px] uppercase tracking-[1.2px] text-ach-navy/55 mb-1">Notable patterns</div>
              <ul className="space-y-1.5 list-disc pl-5 text-[12.5px] text-ach-navy/80">
                {synthesis.notable_patterns.map((p, i) => <li key={i}>{p}</li>)}
              </ul>
            </div>
          )}
        </div>
      ) : (
        <div className="text-[12.5px] text-ach-navy/55 italic">Click Generate to run the AI synthesis. Needs at least 3 narrative entries in the cohort.</div>
      )}
    </div>
  );
}
