import Link from 'next/link';
import { createClient } from '@/lib/supabase/server';
import { resolveCurrentPartner } from '@/lib/partners/resolve-current';
import { PageHeader } from '@/components/ui/page-header';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { EmptyState } from '@/components/ui/empty-state';
import { FileText, Download } from 'lucide-react';

export default async function PartnerReportsPage({
  searchParams,
}: {
  searchParams?: Record<string, string | string[] | undefined>;
}) {
  const partner = await resolveCurrentPartner(searchParams);
  if (!partner) return null;

  const supabase = createClient();

  // Evidence packs that feature this partner (partner appears in featured_partners[])
  const { data: packs } = await supabase
    .from('evidence_packs')
    .select('id, title, funder, funding_window, status, created_at, featured_partners')
    .contains('featured_partners', [partner.id])
    .order('created_at', { ascending: false });

  const packRows = (packs as any[]) ?? [];
  const ready = packRows.filter(r => r.status === 'published');

  return (
    <div className="max-w-6xl mx-auto">
      <PageHeader
        miniLabel="Reports"
        title="Reports & evidence packs"
        description="ACH-generated reports that compile your placements, milestone payments, capability uplift, and audit evidence into a board-ready document."
      />

      <Card className="mb-5">
        <CardContent className="pt-6 text-[13px] text-ach-navy/80 max-w-prose">
          <div className="text-[10.5px] uppercase tracking-[1.2px] text-ach-navy/60 mb-2">What's in a partner evidence pack</div>
          <ul className="space-y-1.5 list-disc pl-5 text-[12.5px]">
            <li>Headline KPIs: placements, retention, milestone payments</li>
            <li>Aggregate HIM capability uplift across your candidates</li>
            <li>Verified audit entries with evidence references</li>
            <li>Inclusion environment scores year-over-year (Training Partners)</li>
            <li>Development Fund contribution and candidate-led outcomes</li>
            <li>Narrative case studies (anonymised unless explicit consent)</li>
          </ul>
          <p className="mt-3 text-[12.5px]">
            Evidence packs are generated by ACH on request, typically quarterly or for board meetings. Contact your ACH partnership lead to request a new pack.
          </p>
        </CardContent>
      </Card>

      <div className="text-[10.5px] uppercase tracking-[1.2px] text-ach-navy/60 mb-3 px-1">
        Available reports ({ready.length})
      </div>

      {ready.length === 0 ? (
        <Card>
          <EmptyState
            icon={<FileText className="h-10 w-10" />}
            title="No reports published yet"
            description="Once ACH has generated and published an evidence pack for your partnership, it will appear here for download."
          />
        </Card>
      ) : (
        <div className="space-y-3">
          {ready.map(p => (
            <Card key={p.id}>
              <CardContent className="pt-5">
                <div className="flex items-start justify-between gap-4">
                  <div className="flex-1">
                    <div className="text-[14px] font-medium text-ach-navy">{p.title}</div>
                    <div className="text-[12px] text-ach-navy/60 mt-1">
                      {[p.funder, p.funding_window].filter(Boolean).join(' · ')}{p.funder ? ' · ' : ''}Generated {new Date(p.created_at).toLocaleDateString('en-GB')}
                    </div>
                  </div>
                  <Badge variant="active">Ready</Badge>
                  <Link
                    href={`/evidence-pack/${p.id}`}
                    target="_blank"
                    className="inline-flex items-center gap-1.5 text-[12px] text-ach-navy underline hover:no-underline"
                  >
                    <Download className="h-3.5 w-3.5" />
                    Download
                  </Link>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
